"
I am a keeper of ai suggested source code.
"
Class {
	#name : 'ChatCodeSuggestedElement',
	#superclass : 'Object',
	#instVars : [
		'package',
		'type',
		'source',
		'versionNumber',
		'name'
	],
	#category : 'ChatBuilder-chat',
	#package : 'ChatBuilder',
	#tag : 'chat'
}

{ #category : 'accessing' }
ChatCodeSuggestedElement >> name [

	^ name
]

{ #category : 'accessing' }
ChatCodeSuggestedElement >> name: anObject [

	name := anObject
]

{ #category : 'accessing' }
ChatCodeSuggestedElement >> package [

	^ package
]

{ #category : 'accessing' }
ChatCodeSuggestedElement >> package: anObject [

	package := anObject
]

{ #category : 'accessing' }
ChatCodeSuggestedElement >> source [

	^ source
]

{ #category : 'accessing' }
ChatCodeSuggestedElement >> source: anObject [

	source := anObject
]

{ #category : 'accessing' }
ChatCodeSuggestedElement >> type [

	^ type
]

{ #category : 'accessing' }
ChatCodeSuggestedElement >> type: anObject [

	type := anObject
]

{ #category : 'accessing' }
ChatCodeSuggestedElement >> versionNumber [

	^ versionNumber
]

{ #category : 'accessing' }
ChatCodeSuggestedElement >> versionNumber: anObject [

	versionNumber := anObject
]
